#!/bin/csh -f

if ($#argv < 1) then
    echo "  Compare code in ./ with code in specified dir"
    echo "  usage: compcd dir"
    exit 1
endif

set d = $1

set list = `ls *.c`
foreach file ($list)
    echo "################ $file	$d/$file"
    diff $file $d/$file
end

set list = `ls *.h`
foreach file ($list)
    echo "################ $file	$d/$file"
    diff $file $d/$file
end

exit
