#!/bin/csh -f 

cvtit /dos2/nice/19980919 -daydir chan=2 comp=0 eof=1000000 sta=XXX ts=60
setenv RESPDB /d1/home/fels/respdb
wseed -sac R262/*SAC
rdseed -df seed -b 400000
exit


R262/1998.09.19-00.15.43.XXX.2-0.info
-------------------------------------
XXX    station
2      channel
0      comp
62.50000000   sample rate
98.09.19-00:15:42.863   start time (no dt correction applied)
98.09.19-00:15:43.741   uncorrected time
??????   system reset time  
??????   external pulse time  
??????  observed dt
??????  estimated dt
+0.1160  adc delay
+0.7620  filter delay
   1017  num of samples

Start time:
43.741 - ( 0.762 + 0.116) = 4.2863000e+01

